#!/usr/bin/env bash
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

export CLIP_STORE="${CLIP_STORE:-$WORKSPACE_ROOT/.build/clip_store}"
exec python3 - "$@" <<'PY'
import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="extract_udp_clips.sh",
        description="Extract ordered media clip bytes from a clips.db generated by the UDP full-run demo."
    )
    parser.add_argument("--db", required=True, help="clip_store database path")
    parser.add_argument("--out-dir", required=True, help="directory for extracted clips")
    parser.add_argument("--session", help="optional session_id filter")
    parser.add_argument("--clip-store", default=os.environ.get("CLIP_STORE", "clip_store"), help="clip_store binary path")
    parser.add_argument("--ffmpeg", default=os.environ.get("FFMPEG", "ffmpeg"), help="ffmpeg binary path")
    parser.add_argument("--no-ffmpeg", action="store_true", help="only extract raw byte ranges; skip ffmpeg conversion")
    return parser.parse_args()


def log(message: str) -> None:
    print(f"[clip-extract] {message}", file=sys.stderr, flush=True)


def require_file(path: str, label: str) -> None:
    if not Path(path).is_file():
        raise SystemExit(f"{label} not found: {path}")


def query_clip_records(args: argparse.Namespace):
    cmd = [args.clip_store, "--db", args.db]
    if args.session:
        cmd.extend(["--prefix", f"{args.session}:"])
    else:
        cmd.append("--list")

    proc = subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"clip_store query failed with rc={proc.returncode}")

    records = []
    for line_no, line in enumerate(proc.stdout.splitlines(), start=1):
        if not line.strip():
            continue
        parts = line.split("\t", 1)
        if len(parts) != 2:
            log(f"skip malformed row line={line_no}")
            continue
        key, value = parts
        try:
            record = json.loads(value)
        except json.JSONDecodeError as exc:
            log(f"skip non-json row key={key}: {exc}")
            continue
        if record.get("type") != "clip":
            continue
        try:
            record["offset"] = int(record["offset"])
            record["length"] = int(record["length"])
        except (KeyError, TypeError, ValueError):
            log(f"skip clip without numeric offset/length key={key}")
            continue
        if "path" not in record or "session_id" not in record:
            log(f"skip clip without path/session_id key={key}")
            continue
        record["_key"] = key
        records.append(record)

    records.sort(key=lambda rec: (str(rec.get("session_id", "")), str(rec.get("path", "")), rec["offset"], int(rec.get("ts", 0))))
    return records


def safe_name(value: object) -> str:
    text = str(value)
    return "".join(ch if ch.isalnum() or ch in ("-", "_") else "_" for ch in text).strip("_") or "clip"


def copy_range(src_path: Path, dst_path: Path, offset: int, length: int) -> None:
    if length <= 0:
        raise ValueError("clip length must be positive")
    with src_path.open("rb") as src, dst_path.open("wb") as dst:
        src.seek(offset)
        remaining = length
        while remaining > 0:
            chunk = src.read(min(1024 * 1024, remaining))
            if not chunk:
                raise EOFError(f"source ended before {length} bytes were read from offset {offset}")
            dst.write(chunk)
            remaining -= len(chunk)


def ffmpeg_convert(ffmpeg: str, src: Path, dst: Path) -> bool:
    cmd = [ffmpeg, "-y", "-hide_banner", "-loglevel", "error", "-i", str(src), "-c", "copy", str(dst)]
    proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=False)
    if proc.returncode == 0:
        return True

    log(f"ffmpeg could not remux {src.name}; keeping raw bytes only")
    if proc.stderr.strip():
        log(proc.stderr.strip().splitlines()[-1])
    if dst.exists():
        dst.unlink()
    return False


def main() -> None:
    args = parse_args()
    require_file(args.db, "clips.db")
    require_file(args.clip_store, "clip_store")

    out_dir = Path(args.out_dir)
    raw_dir = out_dir / "raw"
    media_dir = out_dir / "media"
    raw_dir.mkdir(parents=True, exist_ok=True)
    media_dir.mkdir(parents=True, exist_ok=True)

    records = query_clip_records(args)
    if not records:
        raise SystemExit("no clip records found")

    ffmpeg_available = not args.no_ffmpeg and shutil.which(args.ffmpeg) is not None
    if not args.no_ffmpeg and not ffmpeg_available:
        log(f"ffmpeg not found: {args.ffmpeg}; raw extraction only")

    manifest = []
    combined_by_session = {}
    for index, rec in enumerate(records, start=1):
        src_path = Path(rec["path"])
        require_file(str(src_path), "clip source")

        session = safe_name(rec["session_id"])
        ts = safe_name(rec.get("ts", "0"))
        stem = f"{index:04d}_{session}_{ts}_off{rec['offset']}_len{rec['length']}"
        raw_path = raw_dir / f"{stem}.bin"
        copy_range(src_path, raw_path, rec["offset"], rec["length"])

        media_path = None
        if ffmpeg_available:
            candidate = media_dir / f"{stem}.mp4"
            if ffmpeg_convert(args.ffmpeg, raw_path, candidate):
                media_path = candidate

        combined_by_session.setdefault(session, []).append(raw_path)
        manifest.append({
            "index": index,
            "key": rec["_key"],
            "session_id": rec["session_id"],
            "ts": rec.get("ts"),
            "source": str(src_path),
            "offset": rec["offset"],
            "length": rec["length"],
            "complete": rec.get("complete"),
            "raw": str(raw_path),
            "media": str(media_path) if media_path else None,
        })
        log(f"extracted #{index} session={rec['session_id']} offset={rec['offset']} length={rec['length']} raw={raw_path}")

    for session, raw_paths in combined_by_session.items():
        combined_raw = raw_dir / f"{session}_ordered.bin"
        with combined_raw.open("wb") as dst:
            for raw_path in raw_paths:
                with raw_path.open("rb") as src:
                    shutil.copyfileobj(src, dst)
        combined_media = None
        if ffmpeg_available:
            candidate = media_dir / f"{session}_ordered.mp4"
            if ffmpeg_convert(args.ffmpeg, combined_raw, candidate):
                combined_media = candidate
        log(f"ordered session stream session={session} raw={combined_raw} media={combined_media or 'n/a'}")

    manifest_path = out_dir / "manifest.jsonl"
    with manifest_path.open("w", encoding="utf-8") as fp:
        for item in manifest:
            fp.write(json.dumps(item, separators=(",", ":")) + "\n")
    log(f"wrote manifest={manifest_path}")


if __name__ == "__main__":
    main()
PY
